services:
  frontend:
    build: ./frontend
    container_name: stratify-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  
  backend:
    build: .
    container_name: stratify-backend
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
      - ./backend_api.py:/app/backend_api.py
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_APP=backend_api.py
    stdin_open: true
    tty: true
    command: python backend_api.py
